### ISSUE TITLE
upuptoyou.com 不可用，原因：*.global.ssl.fastly.net 域名被中国封锁

### ISSUE THREAD

**Issue by XIU2** [zhaoolee/OnlineToolsBook#1]
因为 global.ssl.fastly.net 及其子域名均被中国封锁，所以 upuptoyou.com 在中国实际上是不可用的，希望解决该问题。

**Comment by zhaoolee** [comment]
**付费VPN科学上网工具推荐**:  通用网络加速器, 为科技工作者创造价值, 如果你想获得稳定高速的科学上网体验,zhaoolee推荐一家小众但非常稳定的VPN供应商GLaDOS(提供vmess方式)看Youtube1080P不卡,注册登录后, 后台提供iOS端美区APP的下载账号, [点击链接](https://glados.space/landing/OFQTF-AA9NU-I0JVK-11AY8) 可以获得的高速VPN体验

**Comment by XIU2** [comment]
啥玩意？我又不缺这个，我只是提醒你，结果是个打广告的。。。
