### ISSUE TITLE
[自荐]无需上传的批量图片转换器,输出为jpeg、png、webp、webp动画、gif、base64文件。

### ISSUE THREAD

**Issue by renzhezhilu** [zhaoolee/OnlineToolsBook#4]
<img src="https://cdn.jsdelivr.net/gh/renzhezhilu/webp2jpg-online/cdn/logo.svg" alt="webp2jpg-online" width="160" align="bottom" />

在线图片格式转化器, 可将jpeg、jpg、png、gif、webp、svg、ico、bmp文件转化为jpeg、png、webp、ico、gif、base64文件。无需上传文件，本地即可完成转换。
链接：https://renzhezhilu.gitee.io/webp2jpg-online/

<img src="https://camo.githubusercontent.com/bede2ef68cd55f2583af223adf475a1a38de1ec5/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f72656e7a68657a68696c752f77656270326a70672d6f6e6c696e652f63646e2f706167655f75692e6a7067" alt="webp2jpg-online format" width="666" align="bottom" />

✓ 无需上传，使用浏览器自身进行转换
✓ 批量转换输出webp、jpeg、png、base64、8位png(实验)、gif动图(实验)、webp动图(实验)
✓ 输出指定大小(webp、jpeg)(实验)
✓ 输出颜色数量(gif、png-8)
✓ 选项可自定增加或删除并持久化

<img src="https://camo.githubusercontent.com/7eab482bcb47e79b2e8cd234db4269b2ef686f28/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f72656e7a68657a68696c752f77656270326a70672d6f6e6c696e652f63646e2f666f726d6174322e706e67" alt="webp2jpg-online format" width="666" align="bottom" />

### 预览

![](https://github.com/renzhezhilu/webp2jpg-online/raw/master/cdn/v2_demo.gif)

**Comment by zhaoolee** [comment]
已收录， 感谢推荐～
![image](https://user-images.githubusercontent.com/15868458/93038914-c9c71f80-f678-11ea-921f-94397301b8b3.png)
